# Generated by Django 4.1.2 on 2023-06-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('alias_usuario', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('celular', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='idInventario', primary_key=True, serialize=False)),
                ('stock_producto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('cantidad_producto', models.IntegerField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='GamingMarket.cliente')),
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.CASCADE, to='GamingMarket.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('plataforma_producto', models.CharField(max_length=20)),
                ('precio_producto', models.IntegerField()),
                ('imagen_producto', models.ImageField(null=True, upload_to='Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='GamingMarket',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='GamingMarket.producto'),
        ),
    ]
