# Generated by Django 4.1.2 on 2023-06-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0003_remove_cliente_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(max_length=20),
        ),
    ]
