# Generated by Django 4.1.2 on 2023-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0005_producto_genero_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero_producto',
            field=models.IntegerField(),
        ),
    ]
