# Generated by Django 4.1.2 on 2023-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0007_remove_producto_genero_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado_pedido',
            field=models.CharField(max_length=20),
        ),
    ]
