# Generated by Django 4.1.2 on 2023-06-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0008_alter_producto_estado_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estado_pedido',
            new_name='genero_producto',
        ),
    ]
