# Generated by Django 4.1.2 on 2023-06-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0010_alter_cliente_id_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_inventario',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_producto',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
