# Generated by Django 4.1.2 on 2023-06-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0013_pedido_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='plataforma_producto',
            field=models.CharField(choices=[('Super_Nintendo', 'Super Nintendo'), ('Gameboy_Advance', 'Gameboy Advance'), ('Nintendo_64', 'Nintendo 64'), ('PS1', 'PS1'), ('PS2', 'PS2')], max_length=20),
        ),
    ]
