# Generated by Django 4.1.2 on 2023-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingMarket', '0014_alter_producto_plataforma_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='novedad_producto',
            field=models.CharField(choices=[('Juego Nuevo', 'Juego Nuevo'), ('Ya en catalogo', 'Ya en catalogo')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
